spring.application.name=mycode
#
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=asdfghjkl
spring.datasource.driver-class-name=org.postgresql.Driver

# PostgreSQL ke liye sequence strategy fix
spring.jpa.properties.hibernate.id.db_structure_naming=legacy
spring.jpa.hibernate.ddl-auto=update

# Ya seedha dialect set karo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret = ujhsdbABJISdcuiabIdugquidgbQAGwduyagdguyuywdvuywguiwgiug
